### ISSUE TITLE
Tell CodeScene.io authors they use proj IDs in API URIs

### ISSUE THREAD

**Issue by wachulski** [codeconditioner/silver-platter-catalog#1]
Might be a potential security threat (business disclosure) - easy to establish the number of accounts/subscribers in the system. Among many code analysis vendors they are the only ones who do it like this.

**Comment by jumarko** [comment]
Hi, thanks for bringing this up!

It's true that we use simple numeric project IDs but I'm not sure why do you think this is a problem.
Free accounts have public projects by definition and all other accounts' projects are unavailable to unauthorized users. 
I don't see any security hole here.
True, autoincremented IDs can be enumerated more easily than UUIDs et al. but a good authentication/authorization mechanism is much more superior.
Relying on "unguessable" IDs is just a false sense of security.

Do you have a particular thing in mind when suggesting to use other forms of IDs?

Btw. we don't expose account IDs so not sure how you want to use project ids to estimate the number of accounts/subscribers.

## Resources
* https://stackoverflow.com/a/396581/1184752
* https://medium.com/@crussell52/thank-you-for-taking-the-time-to-share-your-experiences-this-is-a-valuable-topic-f097fb7b91a1

**Comment by wachulski** [comment]
Thanks Juraj for the reply. I've answered on Twitter, here for completeness: I find it more Business Intelligence exposure than a security threat. See posts below the SO answer you attached.
