### ISSUE TITLE
Add LGTM results for EntityFrameworkCore & nodatime

### ISSUE THREAD

**Issue by samlanning** [codeconditioner/silver-platter-catalog#3]
Hey There.

Thanks for putting this list together!

I'm with the team behind LGTM, and we do have C# support, so I've started looking into what the situation is with the results for these projects.

* EntityFrameworkCore: It seems that we do have results for this project, viewable here: https://lgtm.com/projects/g/aspnet/EntityFrameworkCore/ [![Total alerts](https://img.shields.io/lgtm/alerts/g/aspnet/EntityFrameworkCore.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/aspnet/EntityFrameworkCore/alerts/)

  Here's the markdown for the alerts badge
  ```markdown
  [![Total alerts](https://img.shields.io/lgtm/alerts/g/aspnet/EntityFrameworkCore.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/aspnet/EntityFrameworkCore/alerts/)
  ```

  As for code quality, this isn't something we currently have a model for for C# as we need a few more projects on lgtm.com before we can do that.

  Sidenote, in the readme you link to [AspNetCore](https://github.com/aspnet/AspNetCore) and not EntityFrameworkCore. Was your intention to list both projects or only one of them? In any case we're looking into why `AspNetCore` is currently not building too.
* Nodatime: It looks like the latest version uses C# 8, which is currently in preview and not yet supported by us. We could look into perhaps analysing an older version rather than the master branch?
* gitextensions: version 3 (master) seems to be windows only. Unfortunately our workers on LGTM.com are all on linux, so it wouldn't be possible to analyse the latest version of this code either. Perhaps we could analyse version 2.5x

**Comment by wachulski** [comment]
Thanks for the valuable input Sam!

1. I fixed the link for EF Core, thanks for spotting this.
2. EF Core results - for the moment being I'm considering putting this as a reference link in the section LGTM is currently positioned. If you get stable results for noda and/or gitext then I can create a row in the table.
3. Nodatime: try this one https://github.com/codeconditioner/nodatime/ (it's April's)
4. GitExt - well, if you're successful with that I may include the results along with a special note.

Yet again - thanks for timely response and your hard work towards making .NET codebases healthier.

**Comment by samlanning** [comment]
Looks like we got the master branch of nodatime working now as well:

https://lgtm.com/projects/g/nodatime/nodatime/alerts/ [![Total alerts](https://img.shields.io/lgtm/alerts/g/nodatime/nodatime.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/nodatime/nodatime/alerts/)

```markdown
[![Total alerts](https://img.shields.io/lgtm/alerts/g/nodatime/nodatime.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/nodatime/nodatime/alerts/)
```

**Comment by samlanning** [comment]
We also have AspNetCore working now if you're interested in that too: https://lgtm.com/projects/g/aspnet/AspNetCore/alerts/?mode=tree

**Comment by wachulski** [comment]
Added a PR. Could you review and say if it's ok for you?

**Comment by samlanning** [comment]
Yeah looks great to me! =)
